### ISSUE TITLE
What's wrong with vuefire/vuexfire?

### ISSUE THREAD

**Issue by kosirm** [quasarframework/app-extension-firebase#3]
Hi, I'm totally new to Quasar framework (just yesterday i discovered it) so my first question was how to connect Firebase. I found this repo and I wonder why not use this project made by Vue core team: [https://vuefire.vuejs.org/](https://vuefire.vuejs.org/) ? Maybe I don't understand how Quasar framework works (please enlighten me), but as far as I understand all vue plugins can be used with Quasar framework, right? Thanks in advance for any reply! BR

**Comment by yusufkandemir** [comment]
Hey @kosirm, you can use Vuefire/Vuexfire to connect Firestore/RTDB to your app. You can use [boot files](https://quasar.dev/quasar-cli/cli-documentation/boot-files) to include Vue plugins or just set up anything before the Vue instance is created. But as for this app-extension, we are planning to also include ways to set up and use other Firebase services such as Firebase Auth, Firebase Messaging(FCM), etc. along Firebase Firestore and RTDB. So just using the Vuefire/Vuexfire will not be sufficient for this app-extension.

**Comment by kosirm** [comment]
Thanks for reply @yusufkandemir ! I'll definetely look into boot files documentation. Good to know that your plugin will offer even better Firebase integration. Good luck with development! Excuse me for using issues as a forum... Best regards!
